# Generated by Django 4.2.7 on 2023-11-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
